#!/bin/sh /etc/rc.common

START=99
STOP=40

start()
{
        echo -n "Testing USB Partition:  "
        e2fsck -p /dev/sda1 &
        sleep 5
        echo -n "Mounting USB drive: "
        mount -t ext3 -o noatime /dev/sda1 /opt
        echo -n "Mounting swap drive: "
        swapon /dev/sda2
        echo "Done."
}
stop()
{
        echo -n "Umounting USB drive:  "
        sync
        sync
        umount /dev/sda1
        echo -n "Umounting swap drive:  "
        sync
        sync
	swapoff /dev/sda2
        echo "Done."
}
restart()
{
        stop
        start
}

